application: lists-themarshians-com
version: 1
runtime: go
api_version: go1

handlers:
  - url: /rest/.*
    script: _go_app
    login: required
    auth_fail_action: unauthorized
    
  - url: /
    static_files: public/index.html
    upload: public/index.html
    login: required
    mime_type: text/html; charset=utf-8

  - url: /(.*\.css)
    mime_type: text/css; charset=utf-8
    static_files: public/\1
    upload: public/(.*\.css)
 
  - url: /(.*\.html)
    mime_type: text/html; charset=utf-8
    static_files: public/\1
    upload: public/(.*\.html)

  - url: /(.*\.ico)
    mime_type: image/x-icon; charset=utf-8
    static_files: public/\1
    upload: public/(.*\.ico)

  - url: /(.*\.js)
    mime_type: text/javascript; charset=utf-8
    static_files: public/\1
    upload: public/(.*\.js)
